sudo: false
dist: xenial
group: stable

jdk: openjdk8

apt:
  packages:
    - openjdk8

before_install:
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
  - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

script:
  - sbt "+ test"

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
